"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { currentUser } from "@/lib/supabase/server";
import { normalizeToKwh } from "@/domain/calculations";
import { renderToBuffer } from "@react-pdf/renderer";
import { DraftAuditPdf } from "@/features/reports/draft-pdf";
import { assertActionOrigin } from "@/lib/security";
import { validateEvidenceUpload } from "@/domain/upload-validation";

type Role="owner"|"editor"|"reviewer"|"viewer";
const roleOrder:Record<Role,number>={viewer:0,reviewer:1,editor:2,owner:3};
function safeActionMessage(error: unknown, fallback: string) { if (error instanceof z.ZodError) return "Check the highlighted information and try again."; if (error instanceof Error && ["Your session has expired. Please sign in again.","You do not have permission to perform that action.","This request could not be verified."].includes(error.message)) return error.message; return fallback; }
async function access(workspaceId:string, minimum:Role="viewer"){const {client,user}=await currentUser();const {data,error}=await client.from("workspace_memberships").select("role").eq("workspace_id",workspaceId).eq("user_id",user.id).single();if(error||!data||roleOrder[data.role as Role]<roleOrder[minimum])throw new Error("You do not have permission to perform that action.");return {client,user,role:data.role as Role};}
async function event(client:any, workspaceId:string, auditId:string|null, entityType:string, entityId:string|undefined, action:string, actorId:string, details:Record<string,unknown>={}){const {error}=await client.rpc("record_audit_event",{target_workspace:workspaceId,target_audit:auditId,target_entity_type:entityType,target_entity_id:entityId??null,target_action:action,target_details:details});if(error)throw new Error("Could not record audit history.");}
const workspaceSchema=z.object({name:z.string().trim().min(2).max(120)});
export async function createWorkspace(_:unknown, formData:FormData){try{await assertActionOrigin();const input=workspaceSchema.parse({name:formData.get("name")});const {client}=await currentUser();const {error}=await client.rpc("create_pilot_workspace",{workspace_name:input.name});if(error)throw new Error(error.message.includes("limit")?"Pilot limit reached: one workspace is available per user. Contact support to expand.":"Could not create workspace.");return {ok:true};}catch(error){return {ok:false,error:safeActionMessage(error,"Could not create workspace.")};}}
const setupSchema=z.object({workspaceId:z.string().uuid(),siteName:z.string().min(2),facilityName:z.string().min(2),auditName:z.string().min(2),objective:z.string().min(4),periodStart:z.string(),periodEnd:z.string(),area:z.coerce.number().positive(),scope:z.string().min(4)});
export async function completeSetup(_:unknown,formData:FormData){try{await assertActionOrigin();const v=setupSchema.parse(Object.fromEntries(formData));const {client,user}=await access(v.workspaceId,"owner");const {data:site,error:siteError}=await client.from("sites").insert({workspace_id:v.workspaceId,name:v.siteName,created_by:user.id,country_code:"IN"}).select().single();if(siteError)throw siteError;const {data:facility,error:facilityError}=await client.from("facilities").insert({workspace_id:v.workspaceId,site_id:site.id,name:v.facilityName,floor_area:v.area,created_by:user.id}).select().single();if(facilityError)throw facilityError;const {data:audit,error:auditError}=await client.from("audits").insert({workspace_id:v.workspaceId,facility_id:facility.id,name:v.auditName,objective:v.objective,period_start:v.periodStart,period_end:v.periodEnd,created_by:user.id}).select().single();if(auditError)throw auditError;const {error:boundaryError}=await client.from("reporting_boundaries").insert({workspace_id:v.workspaceId,audit_id:audit.id,name:"Whole facility",scope_description:v.scope,period_start:v.periodStart,period_end:v.periodEnd,area:v.area,created_by:user.id});if(boundaryError)throw boundaryError;await event(client,v.workspaceId,audit.id,"audit",audit.id,"onboarding_completed",user.id);revalidatePath("/app");return {ok:true};}catch(error){return {ok:false,error:safeActionMessage(error,"Could not save setup.")};}}
const energySchema=z.object({workspaceId:z.string().uuid(),auditId:z.string().uuid(),boundaryId:z.string().uuid(),periodStart:z.string(),periodEnd:z.string(),source:z.enum(["electricity","diesel","petrol","lpg","natural_gas","renewable","other"]),quantity:z.coerce.number().nonnegative(),unit:z.string().min(1),cost:z.coerce.number().nonnegative().optional(),notes:z.string().max(2000).optional()});
export async function createEnergyRecord(_:unknown,formData:FormData){try{await assertActionOrigin();const v=energySchema.parse(Object.fromEntries(formData));const {client,user}=await access(v.workspaceId,"editor");const native=v.source==='electricity'&&v.unit==='kWh'?normalizeToKwh(v.quantity,"kWh"):normalizeToKwh(v.quantity,v.unit,null);const {data,error}=await client.from("energy_records").insert({workspace_id:v.workspaceId,audit_id:v.auditId,boundary_id:v.boundaryId,period_start:v.periodStart,period_end:v.periodEnd,source_category:v.source,raw_quantity:v.quantity,raw_unit:v.unit,normalized_kwh:native.value,conversion_status:native.status,cost_method:"direct_total",direct_cost:v.cost??null,notes:v.notes||null,created_by:user.id}).select("id").single();if(error)throw error;await event(client,v.workspaceId,v.auditId,"energy_record",data.id,"created",user.id);revalidatePath("/app/energy");return {ok:true};}catch(error){return {ok:false,error:safeActionMessage(error,"Could not save energy record.")};}}
export async function reviewEnergyRecord(workspaceId:string,auditId:string,recordId:string,state:"approved"|"rejected"){try{await assertActionOrigin();const {client,user,role}=await access(workspaceId,"reviewer");if(role==='editor') throw new Error("Editors cannot approve records.");const {data:record,error:readError}=await client.from("energy_records").select("id,workspace_id,audit_id").eq("id",recordId).eq("workspace_id",workspaceId).single();if(readError||record.audit_id!==auditId)throw new Error("Record was not found in this audit.");const {error}=await client.from("energy_records").update({review_state:state,reviewed_by:user.id,reviewed_at:new Date().toISOString()}).eq("id",recordId).eq("workspace_id",workspaceId);if(error)throw error;await event(client,workspaceId,auditId,"energy_record",recordId,`review_${state}`,user.id);revalidatePath("/app");return {ok:true};}catch(error){return {ok:false,error:safeActionMessage(error,"Could not review record.")};}}
export async function uploadEvidence(_:unknown,formData:FormData){try{await assertActionOrigin();const workspaceId=z.string().uuid().parse(formData.get("workspaceId"));const auditId=z.string().uuid().parse(formData.get("auditId"));const file=formData.get("file");if(!(file instanceof File)||!validateEvidenceUpload(file,new Uint8Array(await file.slice(0,4096).arrayBuffer())))throw new Error("Use a valid PDF, PNG, JPEG, CSV, or XLSX file up to 10 MB.");const {client,user}=await access(workspaceId,"editor");const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${workspaceId}/${auditId}/${crypto.randomUUID()}-${safeName}`;const {error:uploadError}=await client.storage.from("evidence").upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const {data,error}=await client.from("evidence_documents").insert({workspace_id:workspaceId,audit_id:auditId,storage_path:path,filename:file.name,content_type:file.type,byte_size:file.size,source_provider:String(formData.get("source")||"user upload"),notes:String(formData.get("notes")||""),uploaded_by:user.id}).select("id").single();if(error)throw error;await event(client,workspaceId,auditId,"evidence_document",data.id,"uploaded",user.id);revalidatePath("/app/evidence");return {ok:true};}catch(error){return {ok:false,error:safeActionMessage(error,"Could not upload evidence.")};}}
export async function generateDraftReport(_:unknown,formData:FormData){try{await assertActionOrigin();const workspaceId=z.string().uuid().parse(formData.get('workspaceId'));const auditId=z.string().uuid().parse(formData.get('auditId'));const {client,user}=await access(workspaceId,'reviewer');const [{data:audit},{data:boundary},{data:records},{data:findings},{data:recommendations}]=await Promise.all([client.from('audits').select('name,objective').eq('id',auditId).eq('workspace_id',workspaceId).single(),client.from('reporting_boundaries').select('name,scope_description,period_start,period_end').eq('audit_id',auditId).eq('active',true).single(),client.from('energy_records').select('source_category,raw_quantity,raw_unit,normalized_kwh,review_state').eq('audit_id',auditId).eq('workspace_id',workspaceId),client.from('findings').select('title,observation,review_state').eq('audit_id',auditId).eq('workspace_id',workspaceId),client.from('recommendations').select('intervention,state').eq('audit_id',auditId).eq('workspace_id',workspaceId)]);if(!audit||!boundary)throw new Error('An active audit and reporting boundary are required.');const generatedAt=new Date().toISOString();const pdf=await renderToBuffer(<DraftAuditPdf audit={audit} boundary={boundary} records={records??[]} findings={findings??[]} recommendations={recommendations??[]} generatedAt={generatedAt}/>);const path=`${workspaceId}/${auditId}/${crypto.randomUUID()}.pdf`;const {error:uploadError}=await client.storage.from('reports').upload(path,pdf,{contentType:'application/pdf',upsert:false});if(uploadError)throw uploadError;const {data:report,error}=await client.from('report_exports').insert({workspace_id:workspaceId,audit_id:auditId,storage_path:path,status:'completed',requested_by:user.id,generated_at:generatedAt}).select('id').single();if(error)throw error;await event(client,workspaceId,auditId,'report_export',report.id,'generated',user.id,{version:'0.1'});revalidatePath('/app/reports');return {ok:true};}catch(error){return {ok:false,error:safeActionMessage(error,'Could not generate report.')};}}
