-- Trancense pilot: all tenant data is workspace-scoped and protected by RLS.
create extension if not exists pgcrypto;
create type public.workspace_role as enum ('owner','editor','reviewer','viewer');
create type public.review_state as enum ('draft','approved','rejected');
create type public.recommendation_state as enum ('draft','review','approved','planned','in_progress','completed','verified');

create table public.profiles (id uuid primary key references auth.users on delete cascade, full_name text, organization text, timezone text not null default 'Asia/Kolkata', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.workspaces (id uuid primary key default gen_random_uuid(), name text not null check (char_length(name) between 2 and 120), country_code text not null default 'IN', currency text not null default 'INR', timezone text not null default 'Asia/Kolkata', created_by uuid not null references auth.users, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.workspace_memberships (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, user_id uuid not null references auth.users on delete cascade, role public.workspace_role not null default 'viewer', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,user_id));
create table public.sites (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, name text not null, address_line1 text, address_line2 text, city text, state text, postal_code text, country_code text not null default 'IN', created_by uuid not null references auth.users, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.facilities (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, site_id uuid not null references public.sites on delete cascade, name text not null, facility_type text, floor_area numeric check(floor_area > 0), area_unit text not null default 'm²', created_by uuid not null references auth.users, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.audits (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, facility_id uuid not null references public.facilities on delete cascade, name text not null, objective text, period_start date, period_end date, status text not null default 'active', created_by uuid not null references auth.users, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.reporting_boundaries (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, audit_id uuid not null references public.audits on delete cascade, name text not null default 'Whole facility', scope_description text not null, frequency text not null default 'monthly', period_start date not null, period_end date not null, area numeric check(area > 0), area_unit text default 'm²', active boolean not null default true, created_by uuid not null references auth.users, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.evidence_documents (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, audit_id uuid not null references public.audits on delete cascade, storage_path text not null unique, filename text not null, content_type text not null, byte_size bigint not null check(byte_size > 0 and byte_size <= 10485760), source_provider text, reporting_period date, notes text, review_state public.review_state not null default 'draft', uploaded_by uuid not null references auth.users, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.conversion_factors (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, factor_type text not null, source_category text not null, input_unit text not null, output_unit text not null default 'kWh', value numeric not null check(value >= 0), citation_url text, vintage date, status public.review_state not null default 'draft', version integer not null default 1, notes text, created_by uuid not null references auth.users, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.tariff_assumptions (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, provider text, category text, effective_date date not null, unit_rate numeric not null check(unit_rate >= 0), fixed_charge numeric not null default 0 check(fixed_charge >= 0), demand_charge numeric, taxes numeric not null default 0, source_document_id uuid references public.evidence_documents, entry_method text not null default 'simple_inr_per_kwh', review_state public.review_state not null default 'draft', version integer not null default 1, created_by uuid not null references auth.users, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.energy_records (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, audit_id uuid not null references public.audits on delete cascade, boundary_id uuid not null references public.reporting_boundaries, period_start date not null, period_end date not null, source_category text not null, raw_quantity numeric not null check(raw_quantity >= 0), raw_unit text not null, normalized_kwh numeric check(normalized_kwh >= 0), conversion_status text not null default 'pending', conversion_factor_id uuid references public.conversion_factors, cost_method text not null default 'direct_total', direct_cost numeric check(direct_cost >= 0), unit_rate numeric check(unit_rate >= 0), fixed_charge numeric check(fixed_charge >= 0), currency text not null default 'INR', evidence_document_id uuid references public.evidence_documents, quality_state text not null default 'user_entered', review_state public.review_state not null default 'draft', supersedes_id uuid references public.energy_records, notes text, created_by uuid not null references auth.users, reviewed_by uuid references auth.users, reviewed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(period_end >= period_start));
create table public.equipment (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, facility_id uuid not null references public.facilities on delete cascade, name text not null, category text, location text, quantity integer not null default 1 check(quantity > 0), capacity numeric check(capacity >= 0), operating_hours numeric check(operating_hours >= 0), condition text, quality_label text not null default 'user-entered', notes text, evidence_document_id uuid references public.evidence_documents, created_by uuid not null references auth.users, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.calculations (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, audit_id uuid not null references public.audits on delete cascade, boundary_id uuid references public.reporting_boundaries, metric text not null, value numeric, unit text, formula_name text not null, formula_version text not null, date_range jsonb not null default '{}'::jsonb, input_record_ids jsonb not null default '[]'::jsonb, excluded_record_ids jsonb not null default '[]'::jsonb, assumptions jsonb not null default '{}'::jsonb, warnings jsonb not null default '[]'::jsonb, quality_state text not null, generated_by uuid references auth.users, created_at timestamptz not null default now());
create table public.findings (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, audit_id uuid not null references public.audits on delete cascade, title text not null, category text, observation text not null, confidence text, evidence_ids jsonb not null default '[]'::jsonb, review_state public.review_state not null default 'draft', ai_assisted boolean not null default false, created_by uuid not null references auth.users, reviewed_by uuid references auth.users, reviewed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.recommendations (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, audit_id uuid not null references public.audits on delete cascade, finding_id uuid references public.findings, intervention text not null, affected_system text, assumptions text, dependencies text, risks text, confidence text, estimated_savings_kwh numeric, estimated_annual_cost_savings numeric, implementation_cost numeric, currency text not null default 'INR', payback_years numeric, priority text, owner_id uuid references auth.users, due_date date, notes text, source_ids jsonb not null default '[]'::jsonb, state public.recommendation_state not null default 'draft', created_by uuid not null references auth.users, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.audit_events (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, audit_id uuid references public.audits on delete cascade, entity_type text not null, entity_id uuid, action text not null, details jsonb not null default '{}'::jsonb, actor_id uuid references auth.users, created_at timestamptz not null default now());
create table public.report_exports (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, audit_id uuid not null references public.audits on delete cascade, storage_path text unique, status text not null default 'requested', version text not null default '0.1', requested_by uuid not null references auth.users, generated_at timestamptz, error_code text, created_at timestamptz not null default now());

create or replace function public.is_workspace_member(target_workspace uuid, minimum_role public.workspace_role default 'viewer') returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.workspace_memberships m where m.workspace_id = target_workspace and m.user_id = (select auth.uid()) and (case minimum_role when 'viewer' then true when 'reviewer' then m.role in ('owner','editor','reviewer') when 'editor' then m.role in ('owner','editor') when 'owner' then m.role = 'owner' end)); $$;
revoke all on function public.is_workspace_member(uuid, public.workspace_role) from public;
grant execute on function public.is_workspace_member(uuid, public.workspace_role) to authenticated;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(id, full_name) values(new.id, coalesce(new.raw_user_meta_data->>'full_name','')); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.create_pilot_workspace(workspace_name text) returns uuid language plpgsql security definer set search_path = public as $$ declare new_id uuid; begin if auth.uid() is null then raise exception 'Unauthenticated'; end if; if exists(select 1 from public.workspace_memberships where user_id=auth.uid()) then raise exception 'Pilot workspace limit reached'; end if; insert into public.workspaces(name,created_by) values(workspace_name,auth.uid()) returning id into new_id; insert into public.workspace_memberships(workspace_id,user_id,role) values(new_id,auth.uid(),'owner'); insert into public.audit_events(workspace_id,entity_type,action,actor_id) values(new_id,'workspace','created',auth.uid()); return new_id; end; $$;
revoke all on function public.create_pilot_workspace(text) from public; grant execute on function public.create_pilot_workspace(text) to authenticated;

-- RLS uses only membership rows; never user metadata/JWT role claims.
alter table public.profiles enable row level security;
create policy "profiles self" on public.profiles for all to authenticated using (id=(select auth.uid())) with check (id=(select auth.uid()));
do $$
declare t text;
begin
  foreach t in array array['sites','facilities','audits','reporting_boundaries','evidence_documents','conversion_factors','tariff_assumptions','energy_records','equipment','calculations','findings','recommendations','audit_events','report_exports']
  loop
    execute format('alter table public.%I enable row level security',t);
    execute format('create policy "read member %s" on public.%I for select to authenticated using (public.is_workspace_member(workspace_id,''viewer''))',t,t);
    execute format('create policy "write editor %s" on public.%I for insert to authenticated with check (public.is_workspace_member(workspace_id,''editor''))',t,t);
    execute format('create policy "update editor %s" on public.%I for update to authenticated using (public.is_workspace_member(workspace_id,''editor'')) with check (public.is_workspace_member(workspace_id,''editor''))',t,t);
    execute format('create policy "delete owner %s" on public.%I for delete to authenticated using (public.is_workspace_member(workspace_id,''owner''))',t,t);
  end loop;
end $$;

alter table public.workspaces enable row level security;
create policy "read member workspaces" on public.workspaces for select to authenticated using (public.is_workspace_member(id,'viewer'));
create policy "update owner workspaces" on public.workspaces for update to authenticated using (public.is_workspace_member(id,'owner')) with check (public.is_workspace_member(id,'owner'));
create policy "delete owner workspaces" on public.workspaces for delete to authenticated using (public.is_workspace_member(id,'owner'));

alter table public.workspace_memberships enable row level security;
create policy "read member memberships" on public.workspace_memberships for select to authenticated using (public.is_workspace_member(workspace_id,'viewer'));
create policy "manage members as owner" on public.workspace_memberships for all to authenticated using (public.is_workspace_member(workspace_id,'owner')) with check (public.is_workspace_member(workspace_id,'owner'));
-- Membership and workspace changes remain owner-only after bootstrap; use a server RPC/transaction for initial workspace creation.
drop policy "write editor conversion_factors" on public.conversion_factors; drop policy "update editor conversion_factors" on public.conversion_factors;
create policy "manage factors as owner" on public.conversion_factors for all to authenticated using (public.is_workspace_member(workspace_id,'owner')) with check (public.is_workspace_member(workspace_id,'owner'));
drop policy "write editor tariff_assumptions" on public.tariff_assumptions; drop policy "update editor tariff_assumptions" on public.tariff_assumptions;
create policy "manage tariffs as owner" on public.tariff_assumptions for all to authenticated using (public.is_workspace_member(workspace_id,'owner')) with check (public.is_workspace_member(workspace_id,'owner'));
drop policy "write editor report_exports" on public.report_exports; drop policy "update editor report_exports" on public.report_exports;
create policy "write reports as reviewer" on public.report_exports for insert to authenticated with check (public.is_workspace_member(workspace_id,'reviewer'));
create policy "update reports as reviewer" on public.report_exports for update to authenticated using (public.is_workspace_member(workspace_id,'reviewer')) with check (public.is_workspace_member(workspace_id,'reviewer'));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('evidence','evidence',false,10485760,array['application/pdf','image/png','image/jpeg','text/csv','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']) on conflict (id) do nothing;
create policy "evidence objects read" on storage.objects for select to authenticated using (bucket_id='evidence' and public.is_workspace_member(((storage.foldername(name))[1])::uuid,'viewer'));
create policy "evidence objects upload" on storage.objects for insert to authenticated with check (bucket_id='evidence' and public.is_workspace_member(((storage.foldername(name))[1])::uuid,'editor'));
insert into storage.buckets(id,name,public,file_size_limit) values('reports','reports',false,20971520) on conflict (id) do nothing;
create policy "report objects read" on storage.objects for select to authenticated using (bucket_id='reports' and public.is_workspace_member(((storage.foldername(name))[1])::uuid,'viewer'));
create policy "report objects upload" on storage.objects for insert to authenticated with check (bucket_id='reports' and public.is_workspace_member(((storage.foldername(name))[1])::uuid,'reviewer'));
